name: Diagram

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Create & comment diagram on PR
        uses: erzz/inframap-action@v1
        with:
          plan-files: state.json
          always-run: true
          pr-comment: true
          output-filename: docs/plan.png
